## Projecto República Dominicana

In [1]:
##Correr solo si es requerido
!pip install pyreadstat

Requirement already satisfied: pyreadstat in c:\users\felix.nunez\appdata\local\anaconda3\lib\site-packages (1.3.5)
Requirement already satisfied: narwhals>=2.10.1 in c:\users\felix.nunez\appdata\local\anaconda3\lib\site-packages (from pyreadstat) (2.23.0)
Requirement already satisfied: numpy in c:\users\felix.nunez\appdata\local\anaconda3\lib\site-packages (from pyreadstat) (2.3.5)

In [ ]:
##librerías
import pyreadstat
import pandas as pd
from pathlib import Path #si identificas la ruta de tu archivo, este comando se torna innecesario.
import time

### Definir directorio
```text
carpetax/
  RDproject.ipynb
  data/
    Censo/
      CENSO2010PERSONAS.xlsx
    Encuesta 
      ENHOGAR2010
```

In [3]:
print("Cargando base de datos censal...")
inicio = time.time()
censo2010, meta = pyreadstat.read_sav(r"D://Building Hands-on skills in deterministic and probabilistic record linkage//DataForNow//RepDomProject//data//Censo//CENSO2010RDPERSONAS.sav")
## El objeto censos2010 tiene el dataframe, y meta contiene datos sobre etiquetas y demás.
final = time.time()
print(f"BD Censal cargada en aprox {((final - inicio)/60):.3f} minutos")

print("Cargando base de datos de la encuesta...")
inicio = time.time()
enhogar0910, metaenh09 = pyreadstat.read_sav(r"D://Building Hands-on skills in deterministic and probabilistic record linkage//DataForNow//RepDomProject//data//Encuesta//ENHMiembros2009_2010.sav")
enhogar11, metaenh11 = pyreadstat.read_sav(r"D://Building Hands-on skills in deterministic and probabilistic record linkage//DataForNow//RepDomProject//data//Encuesta//ENHMiembros2011.sav")
final = time.time()
print(f"BD ENHOGAR cargada en aprox: {((final - inicio)/60)} segundos")

Cargando base de datos censal...
BD Censal cargada en aprox 3.850 minutos
Cargando base de datos de la encuesta...
BD ENHOGAR cargada en aprox: 0.5796879291534424 segundos

In [4]:
print(f"Nuestro archivo censo2010 es de tipo: {type(censo2010)}")
print(f"Nuestro archivo meta es de tipo: {type(meta)}")
print("Registros:")
print(f"El total de registros del censo del año 2010 es de {censo2010.shape[0]} filas y {censo2010.shape[1]} columnas")

Nuestro archivo censo2010 es de tipo: <class 'pandas.core.frame.DataFrame'>
Nuestro archivo meta es de tipo: <class 'pyreadstat.pyclasses.metadata_container'>
Registros:
El total de registros del censo del año 2010 es de 9445281 filas y 79 columnas

##### 1. Explorar la base censal (solo para que se muestre como ejercicio previo)


```text
   Nota: Es de importancia crucial tener a mano la boleta censal para ser más precisos en nuestro recorrido
```

In [14]:
print("Variables disponibles en la base censal:")
censo2010.head(7)   # Show 7 rows

Variables disponibles en la base censal:

,REGION,PROVINCIA,MUNICIPIO,DISTRITO,ZONA,SECCION,BARRIO_PARAJE,POLIGONO,AREASUP,SEGMENTO,...,P38_ANOEST,P39R1,P43P44R1,P52R1,P54R1,P45R1_CONDICION_ACTIVIDAD,P56_TOTAL,P57_TOTAL,P39R2,sexo
0,1.0,9.0,1.0,1.0,1.0,1.0,1.0,10.0,2.0,4.0,...,7.0,NaN,1001.0,5.0,7.0,1.0,3.0,3.0,NaN,M
1,1.0,9.0,1.0,1.0,1.0,1.0,1.0,10.0,2.0,4.0,...,7.0,NaN,1001.0,5.0,8.0,5.0,3.0,3.0,NaN,M
2,1.0,9.0,1.0,1.0,1.0,1.0,1.0,10.0,2.0,4.0,...,8.0,NaN,99999.0,5.0,7.0,1.0,NaN,NaN,NaN,H
3,1.0,9.0,1.0,1.0,1.0,1.0,1.0,10.0,2.0,4.0,...,5.0,NaN,1001.0,NaN,NaN,6.0,NaN,NaN,NaN,H
4,1.0,9.0,1.0,1.0,1.0,1.0,1.0,10.0,2.0,4.0,...,2.0,NaN,9001.0,NaN,NaN,NaN,NaN,NaN,NaN,H
5,1.0,9.0,1.0,1.0,1.0,1.0,1.0,10.0,2.0,4.0,...,15.0,634.0,9001.0,3.0,10.0,1.0,3.0,3.0,3.0,M
6,1.0,9.0,1.0,1.0,1.0,1.0,1.0,10.0,2.0,4.0,...,16.0,658.0,9001.0,3.0,7.0,1.0,NaN,NaN,5.0,H

In [ ]:
print(f"Variables en el censo: {meta.column_names_to_labels}")
print(f"Variables en la ENH 09:{metaenh09.column_names_to_labels}")
print(f"Variables en la ENH 11:{metaenh11.column_names_to_labels}")

Variables en el censo: {'REGION': 'Región', 'PROVINCIA': 'Provincia', 'MUNICIPIO': 'Municipio', 'DISTRITO': 'Municipio o Distrito municipal', 'ZONA': 'Zona', 'SECCION': 'Sección', 'BARRIO_PARAJE': 'Barrio o Paraje', 'POLIGONO': 'Polígono', 'AREASUP': 'Area supervisión', 'SEGMENTO': 'Segmento', 'P26_PARENTESCO': '26. Cuál es la relación o parentesco de (NOMBRE) con la jefa o el jefe del hogar?', 'P27_SEXO': '27. Sexo', 'P28A_DIA_NACE': '28a. Día de nacimiento', 'P28B_MES_NACE': '28b. Mes de Nacimiento', 'P28C_ANO_NACE': '28c. Año de Nacimiento', 'P28D_EDAD': '28d. Edad calculada en función a la fecha de nacimiento', 'P29_EDAD_ANOS_CUMPLIDOS': '29. Cuántos años cumplidos tiene (NOMBRE)?', 'P30_DONDE_NACE': '30. Dónde nació (NOMBRE)?', 'P31_MUNICIPIO_NACIO_CODIGO': '31. CODIGO: En qué municipio de la República Dominicana nació?', 'P32_PAIS_NACIO_CODIGO': '32. CODIGO: En qué país nació?', 'P33_ANO_LLEGADA': '33. En qué año llegó (NOMBRE) a vivir a la República Dominicana?', 'P34A_DIFICULTAD_VER': '34a. Para ver, aunque use anteojos o lentes?', 'P34B_DIFICULTAD_OIR': '34b. Para oir, aunque use audifonos?', 'P34C_DIFICULTAD_CAMINAR': '34c. Para caminar o subir escalones?', 'P34D_DIFICULTAD_MOVER_BRAZOS': '34d. Para mover uno o los dos brazos?', 'P34E_DIFICULTAD_MOVER_PIERNA': '34e. Para mover uno o las dos piernas?', 'P34F_DIFICULTAD_RECORDAR': '34f. Para recordar o concentrarse?', 'P34G_DIFICULTAD_AGARRAR_MANO': '34g. Para agarrar objetos y/o abrir recipientes con las manos', 'P34H_DIFICULTAD_HABLAR': '34h. Para hablar?', 'P34I_MUDO': '34i. Es mudo?', 'P34J_PROBLEMAS_MENTALES': '34j. Tiene problemas mentales', 'P34K_FALTA_PIERNA': '34k. Le falta una o las dos piernas?', 'P34L_FALTA_BRAZO': '34l. Le falta uno o los dos brazos?', 'P35_SABE_LEER': '35. Sabe leer y escribir?', 'P36_ASISTE': '36. Asiste o asistió (NOMBRE) a una escuela, colegio o universidad?', 'P37_NIVEL': '37. Cuál es el nivel educativo más alto al que (NOMBRE) asistió en la escuela: primaria o básica, media o secundaria, un', 'P38_ULTIMO_ANO_APROBADO': '38. Cuál fue el último año de estudios que (NOMBRE) aprobó en ese nivel?', 'P39_CARRERA_UNIVERSITARIA_CODIGO': '39. CODIGO: Qué carrera universitaria estudia o estudió (NOMBRE) ?', 'P40_SEGRADUO': '40. Se graduó (NOMBRE) en esa carrera?', 'P41_ANOS_UNIVERSITARIOS': '41. Cuántos años de estudios universitarios completados tiene, incluyendo especialidad, maestría o doctorado?', 'P42_DONDE_VIVIA_112005': '42. En noviembre de 2005 ¿dónde vivía (NOMBRE)?', 'P43_MUNICIPIO_VIVIA_CODIGO': '43. CODIGO: En noviembre de 2005 ¿en qué municipio de la República Dominicana vivía (NOMBRE)?', 'P44_PAIS_VIVIA_CODIGO': '44. CODIGO: En noviembre de 2005 ¿en qué país vivía?', 'P45_TUVO_EMPLEO': '45. Durante la semana pasada tuvo (NOMBRE) algún empleo o trabajo por paga o ganancia, aunque.....?', 'P46_ACTIVIDAD_PORPAGA': '46. Realizó (NOMBRE) durante la semana pasada alguna actividad por paga o ganancia, como......?', 'P47_AYUDO_SINPAGA': '47. Durante la semana pasada ayudó (NOMBRE), sin paga o ganancia, en un negocio, finca o actividad económica de un famil', 'P48_BUSCO_TRABAJO': '48. Durante las últimas cuatro semanas (NOMBRE) buscó trabajo por paga o ganancia o estuvo tratando de establecer ....?', 'P49_QUE_HIZO': '49. A qué se dedicó (NOMBRE) principalmente durante la semana pasada?', 'P50_DISPUESTO_TRABAJAR': '50. La semana pasada ¿habria (NOMBRE) tenido el tiempo y las condiciones necesarias para salir a trabajar si le hubieran', 'P51_TRABAJO_ANTES': '51. Ha trabajado (NOMBRE) antes por paga o ganancia?', 'P52_OCUPACION_CODIGO': '52. CODIGO: Cuál fue la principal ocupación u oficio que desempeñó (NOMBRE) durante la semana pasada o en el último trab', 'P53_CATEGORIA_OCUPACIONAL': '53. En ese trabajo (NOMBRE) es (o era)?', 'P54_RAMA_ACTIVIDAD_CODIGO': '54. CODIGO: A qué se dedica la empresa, negocio o institución en que (NOMBRE) trabaja actualmente o trabajó por última v', 'P55_ESTADO_CIVIL': '55. Está (NOMBRE)  actualmente .....', 'P56A_HIJAS': '56a. En total, Cuántas hijas ha tenido (NOMBRE) aunque hayan fallecido unas pocas horas o días después de haber nacido?', 'P56B_HIJOS': '56b. En total, Cuántos hijos ha tenido (NOMBRE) aunque hayan fallecido unas pocas horas o días después de haber nacido?', 'P56C_NINGUNO': '56c. Ninguna hija o hijo nacido vivo', 'P57A_HIJAS': '57a. Cuántas de estas hijas están vivas actualmente?', 'P57B_HIJOS': '57b. Cuántos de estos hijos están vivos actualmente?', 'P57C_NINGUNO': '57c. Ninguna hija o hijo vivos actualmente', 'P58A_MES_NACIMIENTO': '58a. En qué mes nació la última hija o el último hijo nacido vivo de (NOMBRE)?', 'P58B_ANO_NACIMIENTO': '58b. En qué año nació la última hija o el último hijo nacido vivo de (NOMBRE)?', 'P59_ESTA_VIVA': '59. Está actualmente viva esta última hija o hijo de (NOMBRE)?', 'P60_EDAD_CUANDO_MURIO': '60. Que edad tenía cuando murió?', 'P29R0': 'Edad en grupos quinquenales 0,1,2,... 100 y más', 'P29R1': 'Edad en grupos quinquenales 0-4, .... 85 y más', 'P29R2': 'Edad en grupos quinquenales 0, 1-4, .... 85 y más', 'P29R3': 'Edad en grupos decenales', 'P29R4': 'Edad  en grandes grupos', 'P31P32R1': 'Lugar (municipio - país) de nacimiento', 'P38_ANOEST': 'Años de Estudios calculado', 'P39R1': 'Carrera universitaria que estudia o estudió recodificada a 3 dígitos', 'P43P44R1': 'Lugar (municipio - país) de residencia en 2005', 'P52R1': 'Ocupación u oficio principal que desempeñó recodificada a 1 dígito', 'P54R1': 'Rama de actividad (a qué se dedica la empresa, negocio o institución ...) recodificada a 1 dígito', 'P45R1_CONDICION_ACTIVIDAD': 'Cóndición Actividad Económica # 1', 'P56_TOTAL': '56. Total hijas e hijos tenidos', 'P57_TOTAL': '57. Total hijas e hijos sobrevivientes', 'P39R2': 'Carrera: grupos de educación 2D'}
Variables en la ENH 09:{'estrato': 'Estratos', 'Region': 'Regiones', 'HH7': 'Provincia', 'HH6': 'Zona de residencia', 'HH9': 'Resultado de la entrevista de hogar', 'HH10': 'Respondente del cuestionario del hogar', 'HH11': 'Total de miembros del hogar', 'HH12': 'Total de mujeres de 12-49 años', 'HL3': 'Parentesco con el jefe', 'HL4': 'Es varón o hembra?', 'HL5': 'Edad', 'HL9': 'Madre viva', 'HL10': 'Dónde vive la madre biológica', 'HL11': 'Padre vivo', 'ED2': 'Aguna vez asistió a la escuela o colegio', 'ED3A': 'Nivel de instrucción más alto que aprobó', 'ED3B': 'Curso o año de instrucción más alto que aprobó', 'ED4': 'Se matriculó en el presente año o está inscrito en la universidad', 'ED6A': 'Nivel de educación se matriculó en el  año 2009-2010', 'ED6B': 'Grado de educación  se matriculó en el año 2009-2010', 'CL3': 'Los últimos siete días tuvo un empleo o trabajó por paga aun', 'CL6': 'Los últimos siete días ayudó sin paga en negocio, finca o ac', 'CL8': 'Realizó actividad por paga como vender comida o ropa,coser,u', 'HHWEIGHT': 'Factor deponderación', 'mline': 'Número de linea de la madre', 'melevel1': 'Educacion de la madre', 'helevel': 'Educacion del jefe del hogar', 'HH2A': 'Número de hogar', 'wlthscor': 'REGR factor score   1 for analysis 1', 'wlthind5': 'Grupos quintílicos de riqueza'}
Variables en la ENH 11:{'ESTRATO': 'Estrato', 'REGION': 'Regiones de planificación', 'HPROVI': 'Provincia', 'HZONA': 'Zona', 'FPondera': 'Factor de Ponderación Muestral', 'Fexpansión': 'Factor de Expansión  por UPM', 'HRESUL': 'Resultado  del hogar', 'HMIEMBRO': 'Total de miembros del hogar', 'HVISITAS': 'Número de visitas', 'H202': 'Sexo', 'H203': 'Edad del miembro del hogar', 'H203A': 'Personas con 12 años o más de edad', 'H205': 'Parentesco con el jefe del hogar', 'H206': '¿Tiene acta de namiento?', 'H207': '¿Por qué no ha sido declarado(a)?', 'H208': '¿Actualmente está...?', 'H209': '¿Está vivo el padre biológico?', 'H210': '¿Está viva la madre biológica?', 'H211': '¿Fue vacunado contra sarampión?', 'H212': '¿Sabe leer y escribir?', 'H213': '¿Alguna vez asistió a la escuela o colegio?', 'H214A': 'Año  más alto aprobado', 'H214B': 'Nivel educativo más alto aprobado', 'H215': '¿Se matriculó presente año escolar o universidad?', 'H216A': 'Año o curso se matriculó en el 2010-2011', 'H216B': 'Nivel educativo se matriculó en el año  2010-2011', 'H217': '¿Está asistiendo a clases actualmente?', 'H218': 'Tipo de establecimiento al que asiste', 'H219': '¿Tiene computadroa de uso personal?', 'H220': '¿Usa computadora del hogar o de algún miembro del hogar?', 'H221': '¿Usa computadora fuera del hogar?', 'H301': '¿Tiempo viviendo en este municipio?', 'H302': '¿Lugar de nacimiento?', 'H303': '¿Provincia y municipio de nacimiento?', 'H304': '¿País dónde nació?', 'H305': '¿En que año llego a vivir a RD?', 'H306M': '¿Tiempo viviendo en la RD: cantidad de meses?', 'H306A': '¿Tiempo viviendo en la RD: cantidad de años?', 'H307': '¿Cuánto tiempo más espera vivir en la RD?', 'H308': '¿País donde vivía antes de venir a RD?', 'H401': '¿Los últimos siete días tuvo un empleo o trabajó por paga o ganancia?', 'H402': '¿Realizó la semana pasada alguna actividad como vender comida, ropa, etc?', 'H403': '¿Durante la semana pasada ayudó sin paga o ganancia en un negocio, finca o actividad económica de familiar?', 'H404': '¿Buscó trabajo durante las últimas 4 semanas o trató de estaba tratando de establecer su propio negocio?', 'H405': '¿A que se dedico principalmente durante la semana pasada?', 'H406': '¿La semana pasada habría tenido el tiempo y las condiciones para salir a trabajar?', 'H407': '¿Ha trabajado antes por paga o ganancia?', 'H408': '¿Cuál fue la principal ocupación u oficio que desempeñó la semana pasada?', 'H409': '¿En ese trabajo es o era?', 'H410': '¿A qué se dedica la empresa o negocio en que trabaja o trabajó?', 'H601': '¿Algún miembro tiene tierras sean prestada, propia, alquilada?', 'H601A': '¿Cuánta tareas propias tiene?', 'H601B': '¿Cuántas tareas  arrendadas tiene?', 'H601C': '¿Cuántas tareas a medias, a la tercia, cedidas o prestadadas?', 'H601D': '¿Cuántas tareas sembradas de cultivos agrícolas tiene?', 'H601E': '¿Cuántas tares dedicadas a crianza de animales?', 'H601F': '¿Cuántas tareas de arboles maderables tiene?', 'H601G': '¿Cuántas tareas de montes o bosques tiene?', 'H601H': '¿Cuántas tareas sin sembrar tiene?', 'H601I1': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 1?', 'H601I2': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 2?', 'H601I3': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 3?', 'H601I4': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 4?', 'H601I5': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 5?', 'H601I6': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 6?', 'H601I7': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 7?', 'H601I8': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 8?', 'H601I9': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 9?', 'H601I10': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 10', 'H601J1': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 1?', 'H601J2': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 2?', 'H601J3': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 3?', 'H601J4': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 4?', 'H601J5': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 5?', 'H601J6': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 6?', 'H601J7': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 7?', 'H601J8': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 8?', 'H601J9': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 9?', 'H601J10': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 10?', 'H602': '¿Algún miembro del hogar posee animales para el consumo o para la venta?', 'H602A': '¿Cuántas vacas, toros, becerros o bueyes tiene?', 'H602B': '¿Cuántos cerdos tiene?', 'H602C': '¿Cuántos chivos y ovejos tiene?', 'H602D': '¿Cuántas aves de patio tiene: gallina, pollo, gallos, guineas?', 'H602E': '¿Cuántas aves de granjas  organizadas tiene (gallinas ponedoras, pollos de engorde, etc)?', 'H602F': '¿Cuántos conejos tiene?', 'H602G': '¿Cuántos caballos, burrros y mulos tiene?', 'H602H': '¿Cuántas colmenas, barriles o cajas de abeja tiene?', 'Quintiles': 'Grupo socioeconómico', 'H107': '¿Cuál es el principal combustible que utiliza el hogar para cocinar?', 'Com_Solid': 'Combustible para cocinar'}

In [ ]:
print("ENHOGAR 2009 - 2010:")
print("="*50)
enhogar0910.head(7)   # Show 7 rows

Variables disponibles en la enhogar 2009 - 2010:
==================================================

,estrato,Region,HH7,HH6,HH9,HH10,HH11,HH12,HL3,HL4,...,CL3,CL6,CL8,HHWEIGHT,mline,melevel1,helevel,HH2A,wlthscor,wlthind5
0,1.0,10.0,1.0,1.0,1.0,2.0,4.0,2.0,1.0,1.0,...,1.0,NaN,NaN,2.638838,NaN,NaN,4.0,1.0,2.117738,5.0
1,1.0,10.0,1.0,1.0,1.0,2.0,4.0,2.0,2.0,2.0,...,1.0,NaN,NaN,2.638838,NaN,NaN,4.0,1.0,2.117738,5.0
2,1.0,10.0,1.0,1.0,1.0,2.0,4.0,2.0,3.0,2.0,...,2.0,2.0,2.0,2.638838,1.0,4.0,4.0,1.0,2.117738,5.0
3,1.0,10.0,1.0,1.0,1.0,2.0,4.0,2.0,3.0,1.0,...,2.0,2.0,2.0,2.638838,1.0,4.0,4.0,1.0,2.117738,5.0
4,1.0,10.0,1.0,1.0,1.0,1.0,4.0,1.0,1.0,1.0,...,1.0,NaN,NaN,2.638838,NaN,NaN,4.0,1.0,1.923354,5.0
5,1.0,10.0,1.0,1.0,1.0,1.0,4.0,1.0,2.0,2.0,...,1.0,NaN,NaN,2.638838,NaN,NaN,4.0,1.0,1.923354,5.0
6,1.0,10.0,1.0,1.0,1.0,1.0,4.0,1.0,3.0,1.0,...,2.0,2.0,2.0,2.638838,1.0,4.0,4.0,1.0,1.923354,5.0

In [ ]:
print("ENHOGAR 2011:")
print("="*50)
enhogar11.head(7)  # Show 7 rows

ENHOGAR 2011:
==================================================

,ESTRATO,REGION,HPROVI,HZONA,FPondera,Fexpansión,HRESUL,HMIEMBRO,HVISITAS,H202,...,H602B,H602C,H602D,H602E,H602F,H602G,H602H,Quintiles,H107,Com_Solid
0,1.0,10.0,1.0,1.0,1.084072,147.0,1.0,2.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,1.0
1,1.0,10.0,1.0,1.0,1.084072,147.0,1.0,2.0,3.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,1.0
2,1.0,10.0,1.0,1.0,1.084072,147.0,1.0,7.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0
3,1.0,10.0,1.0,1.0,1.084072,147.0,1.0,7.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0
4,1.0,10.0,1.0,1.0,1.084072,147.0,1.0,7.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0
5,1.0,10.0,1.0,1.0,1.084072,147.0,1.0,7.0,1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0
6,1.0,10.0,1.0,1.0,1.084072,147.0,1.0,7.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,1.0,1.0

In [109]:
########### Homologación de variables
etiqueta_sexo = {
    1: 'Hombre',
    2: 'Mujer'
}
etiqueta_zona = {
    1: 'Urbana',
    2: 'Rural'
}
etiqueta_lectoescritura = {
    1: 'Si',
    2: 'No'
}
etiqueta_region = {
    1: 'Cibao Norte',
    2: 'Cibao Sur',
    3: 'Cibao Nordeste',
    4: 'Cibao Noroeste',
    5: 'Valdesia',
    6: 'Enriquillo',
    7: 'El Valle',
    8: 'Yuma',
    9: 'Higuamo',
    10: 'Ozama'
}
etiqueta_provincia = {
    1: 'Distrito Nacional',
    2: 'Azua',
    3: 'Bahoruco',
    4: 'Barahona',
    5: 'Dajabon',
    6: 'Duarte',
    7: 'Elias Piña',
    8: 'El Seibo',
    9: 'Espaillat',
    10: 'Independencia',
    11: 'La Altagracia',
    12: 'La Romana',
    13: 'La Vega',
    14: 'Maria Trinidad Sanchez',
    15: 'Monte Cristi',
    16: 'Pedernales',
    17: 'Peravia',
    18: 'Puerto Plata',
    19: 'Salcedo',
    20: 'Samana',
    21: 'San Cristobal',
    22: 'San Juan',
    23: 'San Pedro de Macoris',
    24: 'Sanchez Ramírez',
    25: 'Santiago',
    26: 'Santiago Rodriguez',
    27: 'Valverde',
    28: 'Monseñor Nouel',
    29: 'Monte Plata',
    30: 'Hato Mayor',
    31: 'San José de Ocoa',
    32: 'Santo Domingo'
}

In [5]:
print(f"Variables en el censo: {meta.column_names_to_labels}")
print(f"Variables en la ENH 09:{metaenh09.column_names_to_labels}")
print(f"Variables en la ENH 11:{metaenh11.column_names_to_labels}")

Variables en el censo: {'REGION': 'Región', 'PROVINCIA': 'Provincia', 'MUNICIPIO': 'Municipio', 'DISTRITO': 'Municipio o Distrito municipal', 'ZONA': 'Zona', 'SECCION': 'Sección', 'BARRIO_PARAJE': 'Barrio o Paraje', 'POLIGONO': 'Polígono', 'AREASUP': 'Area supervisión', 'SEGMENTO': 'Segmento', 'P26_PARENTESCO': '26. Cuál es la relación o parentesco de (NOMBRE) con la jefa o el jefe del hogar?', 'P27_SEXO': '27. Sexo', 'P28A_DIA_NACE': '28a. Día de nacimiento', 'P28B_MES_NACE': '28b. Mes de Nacimiento', 'P28C_ANO_NACE': '28c. Año de Nacimiento', 'P28D_EDAD': '28d. Edad calculada en función a la fecha de nacimiento', 'P29_EDAD_ANOS_CUMPLIDOS': '29. Cuántos años cumplidos tiene (NOMBRE)?', 'P30_DONDE_NACE': '30. Dónde nació (NOMBRE)?', 'P31_MUNICIPIO_NACIO_CODIGO': '31. CODIGO: En qué municipio de la República Dominicana nació?', 'P32_PAIS_NACIO_CODIGO': '32. CODIGO: En qué país nació?', 'P33_ANO_LLEGADA': '33. En qué año llegó (NOMBRE) a vivir a la República Dominicana?', 'P34A_DIFICULTAD_VER': '34a. Para ver, aunque use anteojos o lentes?', 'P34B_DIFICULTAD_OIR': '34b. Para oir, aunque use audifonos?', 'P34C_DIFICULTAD_CAMINAR': '34c. Para caminar o subir escalones?', 'P34D_DIFICULTAD_MOVER_BRAZOS': '34d. Para mover uno o los dos brazos?', 'P34E_DIFICULTAD_MOVER_PIERNA': '34e. Para mover uno o las dos piernas?', 'P34F_DIFICULTAD_RECORDAR': '34f. Para recordar o concentrarse?', 'P34G_DIFICULTAD_AGARRAR_MANO': '34g. Para agarrar objetos y/o abrir recipientes con las manos', 'P34H_DIFICULTAD_HABLAR': '34h. Para hablar?', 'P34I_MUDO': '34i. Es mudo?', 'P34J_PROBLEMAS_MENTALES': '34j. Tiene problemas mentales', 'P34K_FALTA_PIERNA': '34k. Le falta una o las dos piernas?', 'P34L_FALTA_BRAZO': '34l. Le falta uno o los dos brazos?', 'P35_SABE_LEER': '35. Sabe leer y escribir?', 'P36_ASISTE': '36. Asiste o asistió (NOMBRE) a una escuela, colegio o universidad?', 'P37_NIVEL': '37. Cuál es el nivel educativo más alto al que (NOMBRE) asistió en la escuela: primaria o básica, media o secundaria, un', 'P38_ULTIMO_ANO_APROBADO': '38. Cuál fue el último año de estudios que (NOMBRE) aprobó en ese nivel?', 'P39_CARRERA_UNIVERSITARIA_CODIGO': '39. CODIGO: Qué carrera universitaria estudia o estudió (NOMBRE) ?', 'P40_SEGRADUO': '40. Se graduó (NOMBRE) en esa carrera?', 'P41_ANOS_UNIVERSITARIOS': '41. Cuántos años de estudios universitarios completados tiene, incluyendo especialidad, maestría o doctorado?', 'P42_DONDE_VIVIA_112005': '42. En noviembre de 2005 ¿dónde vivía (NOMBRE)?', 'P43_MUNICIPIO_VIVIA_CODIGO': '43. CODIGO: En noviembre de 2005 ¿en qué municipio de la República Dominicana vivía (NOMBRE)?', 'P44_PAIS_VIVIA_CODIGO': '44. CODIGO: En noviembre de 2005 ¿en qué país vivía?', 'P45_TUVO_EMPLEO': '45. Durante la semana pasada tuvo (NOMBRE) algún empleo o trabajo por paga o ganancia, aunque.....?', 'P46_ACTIVIDAD_PORPAGA': '46. Realizó (NOMBRE) durante la semana pasada alguna actividad por paga o ganancia, como......?', 'P47_AYUDO_SINPAGA': '47. Durante la semana pasada ayudó (NOMBRE), sin paga o ganancia, en un negocio, finca o actividad económica de un famil', 'P48_BUSCO_TRABAJO': '48. Durante las últimas cuatro semanas (NOMBRE) buscó trabajo por paga o ganancia o estuvo tratando de establecer ....?', 'P49_QUE_HIZO': '49. A qué se dedicó (NOMBRE) principalmente durante la semana pasada?', 'P50_DISPUESTO_TRABAJAR': '50. La semana pasada ¿habria (NOMBRE) tenido el tiempo y las condiciones necesarias para salir a trabajar si le hubieran', 'P51_TRABAJO_ANTES': '51. Ha trabajado (NOMBRE) antes por paga o ganancia?', 'P52_OCUPACION_CODIGO': '52. CODIGO: Cuál fue la principal ocupación u oficio que desempeñó (NOMBRE) durante la semana pasada o en el último trab', 'P53_CATEGORIA_OCUPACIONAL': '53. En ese trabajo (NOMBRE) es (o era)?', 'P54_RAMA_ACTIVIDAD_CODIGO': '54. CODIGO: A qué se dedica la empresa, negocio o institución en que (NOMBRE) trabaja actualmente o trabajó por última v', 'P55_ESTADO_CIVIL': '55. Está (NOMBRE)  actualmente .....', 'P56A_HIJAS': '56a. En total, Cuántas hijas ha tenido (NOMBRE) aunque hayan fallecido unas pocas horas o días después de haber nacido?', 'P56B_HIJOS': '56b. En total, Cuántos hijos ha tenido (NOMBRE) aunque hayan fallecido unas pocas horas o días después de haber nacido?', 'P56C_NINGUNO': '56c. Ninguna hija o hijo nacido vivo', 'P57A_HIJAS': '57a. Cuántas de estas hijas están vivas actualmente?', 'P57B_HIJOS': '57b. Cuántos de estos hijos están vivos actualmente?', 'P57C_NINGUNO': '57c. Ninguna hija o hijo vivos actualmente', 'P58A_MES_NACIMIENTO': '58a. En qué mes nació la última hija o el último hijo nacido vivo de (NOMBRE)?', 'P58B_ANO_NACIMIENTO': '58b. En qué año nació la última hija o el último hijo nacido vivo de (NOMBRE)?', 'P59_ESTA_VIVA': '59. Está actualmente viva esta última hija o hijo de (NOMBRE)?', 'P60_EDAD_CUANDO_MURIO': '60. Que edad tenía cuando murió?', 'P29R0': 'Edad en grupos quinquenales 0,1,2,... 100 y más', 'P29R1': 'Edad en grupos quinquenales 0-4, .... 85 y más', 'P29R2': 'Edad en grupos quinquenales 0, 1-4, .... 85 y más', 'P29R3': 'Edad en grupos decenales', 'P29R4': 'Edad  en grandes grupos', 'P31P32R1': 'Lugar (municipio - país) de nacimiento', 'P38_ANOEST': 'Años de Estudios calculado', 'P39R1': 'Carrera universitaria que estudia o estudió recodificada a 3 dígitos', 'P43P44R1': 'Lugar (municipio - país) de residencia en 2005', 'P52R1': 'Ocupación u oficio principal que desempeñó recodificada a 1 dígito', 'P54R1': 'Rama de actividad (a qué se dedica la empresa, negocio o institución ...) recodificada a 1 dígito', 'P45R1_CONDICION_ACTIVIDAD': 'Cóndición Actividad Económica # 1', 'P56_TOTAL': '56. Total hijas e hijos tenidos', 'P57_TOTAL': '57. Total hijas e hijos sobrevivientes', 'P39R2': 'Carrera: grupos de educación 2D'}
Variables en la ENH 09:{'estrato': 'Estratos', 'Region': 'Regiones', 'HH7': 'Provincia', 'HH6': 'Zona de residencia', 'HH9': 'Resultado de la entrevista de hogar', 'HH10': 'Respondente del cuestionario del hogar', 'HH11': 'Total de miembros del hogar', 'HH12': 'Total de mujeres de 12-49 años', 'HL3': 'Parentesco con el jefe', 'HL4': 'Es varón o hembra?', 'HL5': 'Edad', 'HL9': 'Madre viva', 'HL10': 'Dónde vive la madre biológica', 'HL11': 'Padre vivo', 'ED2': 'Aguna vez asistió a la escuela o colegio', 'ED3A': 'Nivel de instrucción más alto que aprobó', 'ED3B': 'Curso o año de instrucción más alto que aprobó', 'ED4': 'Se matriculó en el presente año o está inscrito en la universidad', 'ED6A': 'Nivel de educación se matriculó en el  año 2009-2010', 'ED6B': 'Grado de educación  se matriculó en el año 2009-2010', 'CL3': 'Los últimos siete días tuvo un empleo o trabajó por paga aun', 'CL6': 'Los últimos siete días ayudó sin paga en negocio, finca o ac', 'CL8': 'Realizó actividad por paga como vender comida o ropa,coser,u', 'HHWEIGHT': 'Factor deponderación', 'mline': 'Número de linea de la madre', 'melevel1': 'Educacion de la madre', 'helevel': 'Educacion del jefe del hogar', 'HH2A': 'Número de hogar', 'wlthscor': 'REGR factor score   1 for analysis 1', 'wlthind5': 'Grupos quintílicos de riqueza'}
Variables en la ENH 11:{'ESTRATO': 'Estrato', 'REGION': 'Regiones de planificación', 'HPROVI': 'Provincia', 'HZONA': 'Zona', 'FPondera': 'Factor de Ponderación Muestral', 'Fexpansión': 'Factor de Expansión  por UPM', 'HRESUL': 'Resultado  del hogar', 'HMIEMBRO': 'Total de miembros del hogar', 'HVISITAS': 'Número de visitas', 'H202': 'Sexo', 'H203': 'Edad del miembro del hogar', 'H203A': 'Personas con 12 años o más de edad', 'H205': 'Parentesco con el jefe del hogar', 'H206': '¿Tiene acta de namiento?', 'H207': '¿Por qué no ha sido declarado(a)?', 'H208': '¿Actualmente está...?', 'H209': '¿Está vivo el padre biológico?', 'H210': '¿Está viva la madre biológica?', 'H211': '¿Fue vacunado contra sarampión?', 'H212': '¿Sabe leer y escribir?', 'H213': '¿Alguna vez asistió a la escuela o colegio?', 'H214A': 'Año  más alto aprobado', 'H214B': 'Nivel educativo más alto aprobado', 'H215': '¿Se matriculó presente año escolar o universidad?', 'H216A': 'Año o curso se matriculó en el 2010-2011', 'H216B': 'Nivel educativo se matriculó en el año  2010-2011', 'H217': '¿Está asistiendo a clases actualmente?', 'H218': 'Tipo de establecimiento al que asiste', 'H219': '¿Tiene computadroa de uso personal?', 'H220': '¿Usa computadora del hogar o de algún miembro del hogar?', 'H221': '¿Usa computadora fuera del hogar?', 'H301': '¿Tiempo viviendo en este municipio?', 'H302': '¿Lugar de nacimiento?', 'H303': '¿Provincia y municipio de nacimiento?', 'H304': '¿País dónde nació?', 'H305': '¿En que año llego a vivir a RD?', 'H306M': '¿Tiempo viviendo en la RD: cantidad de meses?', 'H306A': '¿Tiempo viviendo en la RD: cantidad de años?', 'H307': '¿Cuánto tiempo más espera vivir en la RD?', 'H308': '¿País donde vivía antes de venir a RD?', 'H401': '¿Los últimos siete días tuvo un empleo o trabajó por paga o ganancia?', 'H402': '¿Realizó la semana pasada alguna actividad como vender comida, ropa, etc?', 'H403': '¿Durante la semana pasada ayudó sin paga o ganancia en un negocio, finca o actividad económica de familiar?', 'H404': '¿Buscó trabajo durante las últimas 4 semanas o trató de estaba tratando de establecer su propio negocio?', 'H405': '¿A que se dedico principalmente durante la semana pasada?', 'H406': '¿La semana pasada habría tenido el tiempo y las condiciones para salir a trabajar?', 'H407': '¿Ha trabajado antes por paga o ganancia?', 'H408': '¿Cuál fue la principal ocupación u oficio que desempeñó la semana pasada?', 'H409': '¿En ese trabajo es o era?', 'H410': '¿A qué se dedica la empresa o negocio en que trabaja o trabajó?', 'H601': '¿Algún miembro tiene tierras sean prestada, propia, alquilada?', 'H601A': '¿Cuánta tareas propias tiene?', 'H601B': '¿Cuántas tareas  arrendadas tiene?', 'H601C': '¿Cuántas tareas a medias, a la tercia, cedidas o prestadadas?', 'H601D': '¿Cuántas tareas sembradas de cultivos agrícolas tiene?', 'H601E': '¿Cuántas tares dedicadas a crianza de animales?', 'H601F': '¿Cuántas tareas de arboles maderables tiene?', 'H601G': '¿Cuántas tareas de montes o bosques tiene?', 'H601H': '¿Cuántas tareas sin sembrar tiene?', 'H601I1': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 1?', 'H601I2': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 2?', 'H601I3': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 3?', 'H601I4': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 4?', 'H601I5': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 5?', 'H601I6': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 6?', 'H601I7': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 7?', 'H601I8': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 8?', 'H601I9': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 9?', 'H601I10': '¿Cuáles productos cosechó durante los últimos 12 meses: Producto 10', 'H601J1': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 1?', 'H601J2': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 2?', 'H601J3': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 3?', 'H601J4': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 4?', 'H601J5': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 5?', 'H601J6': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 6?', 'H601J7': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 7?', 'H601J8': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 8?', 'H601J9': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 9?', 'H601J10': '¿Cuántas tareas cosechó en los últimos 12 meses: Tarea 10?', 'H602': '¿Algún miembro del hogar posee animales para el consumo o para la venta?', 'H602A': '¿Cuántas vacas, toros, becerros o bueyes tiene?', 'H602B': '¿Cuántos cerdos tiene?', 'H602C': '¿Cuántos chivos y ovejos tiene?', 'H602D': '¿Cuántas aves de patio tiene: gallina, pollo, gallos, guineas?', 'H602E': '¿Cuántas aves de granjas  organizadas tiene (gallinas ponedoras, pollos de engorde, etc)?', 'H602F': '¿Cuántos conejos tiene?', 'H602G': '¿Cuántos caballos, burrros y mulos tiene?', 'H602H': '¿Cuántas colmenas, barriles o cajas de abeja tiene?', 'Quintiles': 'Grupo socioeconómico', 'H107': '¿Cuál es el principal combustible que utiliza el hogar para cocinar?', 'Com_Solid': 'Combustible para cocinar'}

In [ ]:
print("Iniciando creación de variables homologadas...")
inicio = time.time()
#sexo
censo2010['sexo'] = censo2010['P27_SEXO'].map(etiqueta_sexo)
enhogar0910['sexo'] = enhogar0910['HL4'].map(etiqueta_sexo)
enhogar11['sexo'] = enhogar11['H202'].map(etiqueta_sexo)

#zona
censo2010['zona'] = censo2010['ZONA'].map(etiqueta_zona)
enhogar0910['zona'] = enhogar0910['HH6'].map(etiqueta_zona)
enhogar11['zona'] = enhogar11['HZONA'].map(etiqueta_zona)

#lectoescritura
censo2010['lectoescritura'] = censo2010['P35_SABE_LEER'].map(etiqueta_lectoescritura)
#la enh 2009 no trajo lectoescritura
enhogar11['lectoescritura'] = enhogar11['H212'].map(etiqueta_lectoescritura)

#region
censo2010['region_clean'] = censo2010['REGION'].map(etiqueta_region)
enhogar0910['region_clean'] = enhogar0910['Region'].map(etiqueta_region)
enhogar11['region_clean'] = enhogar11['REGION'].map(etiqueta_region)

#provincia
censo2010['provincia_clean'] = censo2010['PROVINCIA'].map(etiqueta_provincia)
enhogar0910['provincia_clean'] = enhogar0910['HH7'].map(etiqueta_provincia)
enhogar11['provincia_clean'] = enhogar11['HPROVI'].map(etiqueta_provincia)
final = time.time()
print(f"Proceso terminado en {(final - inicio):.2f} segundos")

Iniciando creación de variables homologadas...
Proceso terminado en 1.63 segundos

In [112]:
print("="*50)
print("Generando frecuencias del sexo...")
inicio = time.time()
print(f"Censo: {censo2010['sexo'].value_counts()} →→→→→→→→→→→→ ENHOGAR 2009- 2010  {enhogar0910['sexo'].value_counts()} →→→→→→→→→→→→ ENHOGAR 2011 \n {enhogar11['sexo'].value_counts()} ")
final = time.time()
print(f"Frecuencia sexo generada en {((final - inicio))} segundos")
print("="*70)
print()

print("Generando frecuencias de la zona...")
inicio = time.time()
print(f"Censo: {censo2010['zona'].value_counts()} →→→→→→→→→→→→ ENHOGAR 2009- 2010  {enhogar0910['zona'].value_counts()} →→→→→→→→→→→→ ENHOGAR 2011 \n {enhogar11['zona'].value_counts()} ")
final = time.time()
print(f"Frecuencia zona generada en {((final - inicio))} segundos")
print("="*70)
print()

print("Generando frecuencias de la lectoescritura...")
inicio = time.time()
print(f"Censo: {censo2010['lectoescritura'].value_counts()}→→→→→→→→→→→→ ENHOGAR 2011 \n {enhogar11['lectoescritura'].value_counts()} ")
final = time.time()
print(f"Frecuencia lectoescritura generada en {((final - inicio))} segundos")
print("="*70)
print()

==================================================
Generando frecuencias del sexo...
Censo: sexo
Hombre    4739038
Mujer     4706243
Name: count, dtype: int64 →→→→→→→→→→→→ ENHOGAR 2009- 2010  sexo
Hombre    16095
Mujer     15774
Name: count, dtype: int64 →→→→→→→→→→→→ ENHOGAR 2011
 sexo
Hombre    28172
Mujer     28080
Name: count, dtype: int64
Frecuencia sexo generada en 0.47472572326660156 segundos
======================================================================

Generando frecuencias de la zona...
Censo: zona
Urbana    7013575
Rural     2431706
Name: count, dtype: int64 →→→→→→→→→→→→ ENHOGAR 2009- 2010  zona
Urbana    19720
Rural     12149
Name: count, dtype: int64 →→→→→→→→→→→→ ENHOGAR 2011
 zona
Urbana    36788
Rural     19464
Name: count, dtype: int64
Frecuencia zona generada en 0.3331475257873535 segundos
======================================================================

Generando frecuencias de la lectoescritura...
Censo: lectoescritura
Si    7257221
No    1630423
Name: count, dtype: int64→→→→→→→→→→→→ ENHOGAR 2011
 lectoescritura
Si    44338
No     8372
Name: count, dtype: int64
Frecuencia lectoescritura generada en 0.3337364196777344 segundos
======================================================================

#### El estado conyugal

Según el listin diario (https://www.diariolibre.com/actualidad/en-los-ltimos-cinco-aos-los-divorcios-en-la-repblica-dominicana-promedian-ms-de-17-mil-LNDL416508), para el año 2011 se registró un total de 17,181 parejas divorciadas. Suponiendo un comportamiento lineal durante el año, habría aproximadamente 1,431.75 divorcios por mes, lo que supone que, al 20 de septiembre, donde inició el levantamiento de la ENHOGAR 2011, se habían divorciado aproximadamente 13, 840.2 personas. Esto solo en este estado conyugal. No sabemos los cambios surgidos en las otras categorías.

Por esta razón, es menester evaluar profundamente si se podrá tomar el estado conyugal como una variable confiable para el linkage.

`Nota: Debido a que las fuentes levantan información de forma diferente, será necesario hacer la creación del estado conyugal a mano.`

In [117]:
print(f"La variable H208, cuya forma de preguntar fue '{metaenh11.column_names_to_labels['H208']}', tiene las categorías:")  #ver label de la variable
print(metaenh11.value_labels[metaenh11.variable_to_label['H208']])

La variable H208, cuya forma de preguntar fue '¿Actualmente está...?', tiene las categorías:
{1.0: 'Casado(a)', 2.0: 'Unido(a)', 3.0: 'Viudo(a)', 4.0: 'Divorciado(a)', 5.0: 'Separado de matrimonio legal o religioso', 6.0: 'Separado(a) de unión libre', 7.0: 'Soltero(a)', 9.0: 'Sin información'}

In [ ]:
# estado conyugal
print(f"Estado conyugal en la ENH 2011: {enhogar11['H208'].value_counts().sort_index()}")  #sort_index() muestra el orden de la variable, no de los pesos de la frecuencia.
print("="*50)
print("La ENHOGAR 200 no trajo la variable sobre estado conyugal")
print("="*50)

enhogar11['estado_conyugal'] = enhogar11['H208'].map(
    {
    1: 'casado',
    2: 'unido',
    3: 'viudo',
    4: 'divorciado',
    5: 'separado de un matrimonio',
    6: 'separado de una union libre',
    7: 'soltero',
    9: 'SinInfo'
}
)

print(f"Estado conyugal : {enhogar11['estado_conyugal'].value_counts()}")

Estado conyugal en la ENH 2011: H208
1.0     6333
2.0    13831
3.0     2023
4.0      486
5.0      490
6.0     5713
7.0    13840
9.0      332
Name: count, dtype: int64
==================================================
La ENHOGAR 200 no trajo la variable sobre estado conyugal
==================================================
Estado conyugal : estado_conyugal
soltero                        13840
unido                          13831
casado                          6333
separado de una union libre     5713
viudo                           2023
separado de un matrimonio        490
divorciado                       486
SinInfo                          332
Name: count, dtype: int64

In [118]:

print(f"La variable P55_ESTADO_CIVIL, cuya forma de preguntar fue '{meta.column_names_to_labels['P55_ESTADO_CIVIL']}', tiene las categorías:")  #ver label de la variable
est_con_censo = meta.variable_to_label['P55_ESTADO_CIVIL']

print(meta.value_labels[est_con_censo])

censo2010['estado_conyugal'] = censo2010['P55_ESTADO_CIVIL'].map(
    {
    1: 'separado de un matrimonio',
    2: 'divorciado',
    3: 'viudo',
    4: 'separado de una union libre',
    5: 'casado',
    6: 'unido',
    7: 'soltero',
    9: 'SinInfo'
    }
)

print("="*50)
print(f"Estado conyugal en el censo: {censo2010['estado_conyugal'].value_counts()}")

La variable P55_ESTADO_CIVIL, cuya forma de preguntar fue '55. Está (NOMBRE)  actualmente .....', tiene las categorías:
{1.0: 'Separado(a) de un matrimonio', 2.0: 'Divorciado(a)', 3.0: 'Viudo(a)', 4.0: 'Separado(a) de una unión libre', 5.0: 'Casado(a)', 6.0: 'Unido(a)', 7.0: 'Nunca se ha casado ni unido', 9.0: 'No declarado'}
==================================================
Estado conyugal en el censo: estado_conyugal
unido                          2318639
soltero                        1783601
casado                         1152657
separado de una union libre     838682
viudo                           287142
divorciado                      137403
separado de un matrimonio       118184
SinInfo                             46
Name: count, dtype: int64

In [29]:
print(f"Frecuencia de la var sexo: \n {censo2010['P27_SEXO'].value_counts()}")
print("-"*25)
print(f"Frecuencia de la var sexo: \n {censo2010['REGION'].value_counts()}")

Frecuencia de la var sexo:
 P27_SEXO
1.0    4739038
2.0    4706243
Name: count, dtype: int64
-------------------------
Frecuencia de la var sexo:
 REGION
10.0    3339410
1.0     1516957
5.0     1028129
2.0      710821
3.0      624186
8.0      606323
9.0      561431
4.0      394068
6.0      368594
7.0      295362
Name: count, dtype: int64

#### La jefatura del hogar

In [6]:
print(f"censo: {meta.value_labels[meta.variable_to_label['P26_PARENTESCO']]}")
print(f"ENH 09:{metaenh09.value_labels[metaenh09.variable_to_label['HL3']]}")
print(f"ENH 11:{metaenh11.value_labels[metaenh11.variable_to_label['H205']]}")

censo: {1.0: 'Jefa o jefe', 2.0: 'Esposo (a) o compañero (a)', 3.0: 'Hijo (a)', 4.0: 'Hijo (a) de crianza', 5.0: 'Padre o madre', 6.0: 'Nieto (a)', 7.0: 'Suegro (a)', 8.0: 'Abuelo (a)', 9.0: 'Hermano (a)', 10.0: 'Empleado (a) doméstico (a)', 11.0: 'Otro pariente', 12.0: 'Yerno o nuera', 13.0: 'No pariente', 14.0: 'Miembro de un hogar colectivo'}
ENH 09:{1.0: 'El(la) jefe(a)', 2.0: ' Esposo(a) o Compañero(a)', 3.0: 'Hijo(a)', 4.0: 'Yerno o nuera', 5.0: 'Nieto(a)', 6.0: 'Padre/Madre', 7.0: 'Suegro/Suegra', 8.0: 'Hermano(a)', 9.0: 'Cuñado(a)', 10.0: 'Tio(a)', 11.0: 'Sobrino(a) biologico', 12.0: 'Sobrino(a) no biologico', 13.0: 'Otro Pariente', 14.0: 'Adoptado/hijastro', 15.0: 'No pariente', 16.0: 'Servicio domestico', 97.0: 'Incossistente', 98.0: 'No sabe', 99.0: 'Sin información'}
ENH 11:{1.0: 'El (la) Jefe(a)', 2.0: 'Esposo(a) o compañero(a)', 3.0: 'Hijo(a)', 4.0: 'Yerno o nuera', 5.0: 'Nieto(a)', 6.0: 'Padre o madre', 7.0: 'Suegro(a)', 8.0: 'Hermano(a)', 9.0: 'Cuñado(a)', 10.0: 'Tio(a)', 11.0: 'Sobrino(a)', 12.0: 'Abuelo(a)', 13.0: 'Otro pariente', 14.0: 'No pariente', 15.0: 'Servicio domestico', 99.0: 'Sin información'}

In [8]:

censo2010['jefe_hogar'] = censo2010['P26_PARENTESCO'].map({
    1: 'Jefe/a',
    2: 'Esposo/a',
    3: 'Hijo/a',
    4: 'Hijo_crianza',
    5: 'Padre/Madre',
    6: 'Nieto',
    7: 'Suegro/a',
    8: 'Abuelo/a',
    9: 'Hermano/a',
    10: 'Empleado_domestico',
    11: 'Otro_pariente',
    12: 'Yerno_Nuera',
    13: 'No_pariente',
    14: 'Miembro_hogar_colectivo'
    }
)
enhogar0910['jefe_hogar'] = enhogar0910['HL3'].map({
    1: 'Jefe/a',
    2: 'Esposo/a',
    3: 'Hijo/a',
    4: 'Yerno_Nuera',
    5: 'Nieto',
    6: 'Padre/Madre',
    7: 'Suegro/a',
    8: 'Hermano/a',
    9: 'cuñado/a',
    10: 'Tio/a',
    11: 'Sobrino_biologico',
    12: 'Sobrino_no_biologico',
    13: 'Otro_pariente',
    14: 'Hijo_crianza',
    15: 'No_pariente',
    16: 'Empleado_domestico',
    97: 'Inconsistente',
    98: 'No_sabe',
    99: 'Sin_información'
    }
)

enhogar11['jefe_hogar'] = enhogar11['H205'].map({
    1: 'Jefe/a',
    2: 'Esposo/a',
    3: 'Hijo/a',
    4: 'Yerno_Nuera',
    5: 'Nieto',
    6: 'Padre/Madre',
    7: 'Suegro/a',
    8: 'Hermano/a',
    9: 'cuñado/a',
    10: 'Tio/a',
    11: 'Sobrino',
    12: 'Abuelo',
    13: 'Otro_pariente',
    14: 'No_pariente',
    15: 'Empleado_domestico',
    99: 'Sin_información'
    }
)

In [25]:
print(f"Jefe hogar enh 2009:\n {pd.concat
                              (
                                  [
                                      censo2010['jefe_hogar'].value_counts(),
                                      pd.Series({'Total': censo2010['jefe_hogar'].notna().sum()})
                                  ]
                               )
                             }"
    )

Jefe hogar enh 2009:
 Hijo/a                     3538408
Jefe/a                     2671979
Esposo/a                   1443521
Nieto                       685446
Otro_pariente               436526
Hijo_crianza                186080
Hermano/a                   175713
No_pariente                 110129
Padre/Madre                  67112
Yerno_Nuera                  66763
Miembro_hogar_colectivo      23534
Suegro/a                     19356
Empleado_domestico           15616
Abuelo/a                      5098
Total                      9445281
dtype: int64

In [22]:
print(f"Jefe hogar enh 2009:\n {pd.concat
                              (
                                  [
                                      enhogar0910['jefe_hogar'].value_counts(),
                                      pd.Series({'Total': enhogar0910['jefe_hogar'].notna().sum()})
                                  ]
                               )
                             }")

Jefe hogar enh 2009:
 Hijo/a                  12122
Jefe/a                   8883
Esposo/a                 5170
Nieto                    2868
Hijo_crianza              768
Hermano/a                 389
No_pariente               321
Sobrino_biologico         302
Otro_pariente             300
Padre/Madre               210
Yerno_Nuera               194
cuñado/a                  109
Sobrino_no_biologico      100
Suegro/a                   78
Tio/a                      33
Sin_información            14
Empleado_domestico          8
Total                   31869
dtype: int64

In [26]:
print(f"Jefe hogar enh 2011:\n {pd.concat(
    [
    enhogar11['jefe_hogar'].value_counts(),
    pd.Series({'Total': enhogar11['jefe_hogar'].notna().sum()})
    ]
)}")

Jefe hogar enh 2011:
 Hijo/a                21215
Jefe/a                15964
Esposo/a               8996
Nieto                  4568
Otro_pariente          1396
No_pariente            1077
Hermano/a               889
Sobrino                 763
Padre/Madre             447
Yerno_Nuera             441
cuñado/a                217
Suegro/a                122
Sin_información          69
Tio/a                    42
Abuelo                   26
Empleado_domestico       20
Total                 56252
dtype: int64

##### 1. Explorar las bases enhogar

In [7]:
print("Variables disponibles en la base:")
print()
enhogar11.columns

Variables disponibles en la base:

Index(['ESTRATO', 'REGION', 'HPROVI', 'HZONA', 'FPondera', 'Fexpansión',
       'HRESUL', 'HMIEMBRO', 'HVISITAS', 'H202', 'H203', 'H203A', 'H205',
       'H206', 'H207', 'H208', 'H209', 'H210', 'H211', 'H212', 'H213', 'H214A',
       'H214B', 'H215', 'H216A', 'H216B', 'H217', 'H218', 'H219', 'H220',
       'H221', 'H301', 'H302', 'H303', 'H304', 'H305', 'H306M', 'H306A',
       'H307', 'H308', 'H401', 'H402', 'H403', 'H404', 'H405', 'H406', 'H407',
       'H408', 'H409', 'H410', 'H601', 'H601A', 'H601B', 'H601C', 'H601D',
       'H601E', 'H601F', 'H601G', 'H601H', 'H601I1', 'H601I2', 'H601I3',
       'H601I4', 'H601I5', 'H601I6', 'H601I7', 'H601I8', 'H601I9', 'H601I10',
       'H601J1', 'H601J2', 'H601J3', 'H601J4', 'H601J5', 'H601J6', 'H601J7',
       'H601J8', 'H601J9', 'H601J10', 'H602', 'H602A', 'H602B', 'H602C',
       'H602D', 'H602E', 'H602F', 'H602G', 'H602H', 'Quintiles', 'H107',
       'Com_Solid'],
      dtype='object')